# Generated by Django 2.1.4 on 2019-04-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_voter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
